version: '3'
services:
  # see https://docs.drone.io/server/provider/gogs/
  drone-server:
    image: drone/drone:latest
    ports:
      - 8080:80
      - 8843:443
    volumes:
      - ./drone:/data
    environment:
      - DRONE_OPEN=true
      - DRONE_AGENTS_ENABLED=true
      # gogs server address(地址一定要对, 生产环境建议用域名)
      - DRONE_GOGS_SERVER=http://192.168.1.89:3000
      # remember replace the secret with your secret
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
      # 192.168.1.89:8080
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
    restart: always
  drone-runner:
    image: drone/drone-runner-docker:latest
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7300:3000
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=192.168.1.89:8080
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
    restart: always