apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-use
---
# 官方说明: https://cert-manager.io/docs/configuration/acme/
# 创建ClusterIssuer资源
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  namespace: cert-manager-use
spec:
  acme:
    # acme 协议的服务端，由官方给出
    server: https://acme-v02.api.letsencrypt.org/directory
    # 邮箱，证书快过期的时候会有邮件提醒，不过cert-manager会利用acme协议自动给我们重新颁发证书来续期
    email: swh-email@qq.com
    # 指示此签发机构的私钥将要存储到哪个Secret对象中
    privateKeySecretRef:
      name: cluster-issuer
    # 指示签发机构使用HTTP-01的方式进行acme协议 (还可以用DNS方式，acme协议的目的是证明这台机器和域名都是属于你的，然后才准许给你颁发证书)
    solvers:
      - http01:
          ingress:
            class: nginx