kind: pipeline
type: docker
name: default

# 要执行的步骤
steps:
  - name: test
    image: golang
    commands:
      - # 将go包代理指向国内， 避免无法访问
      - go env -w GOPROXY=https://goproxy.cn
      - go test
      - go build
      - go test -v -coverprofile cover.out test/mytest
