apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-use
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: traefik-signed
  namespace: cert-manager-use
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned