name: project
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is projectTest
    name: projectTest
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: mockTest
#        uses: shanwenhao1/bookReadingNote
        run: go test bookReadingNote/project/mock/myMock
#        go test bookReadingNote/project/mock/mockSample