name: project
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
#    tags:
#      - v1
#  paths:
##    - 'test/*'
#    - 'bookReadingNote/project/mock/mockSample'

jobs:
  test:
    name: Test on node
    runs-on: ubuntu-latest

    steps:
    - uses: shanwenhao1/bookReadingNote@v1

    - name: mockTest
      run: go test -v -coverprofile cover.out bookReadingNote\project\mock\myMock
