name: project
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
#    tags:
#      - v1
#  paths:
#    - 'test/*'

jobs:
  build:
    # Job name is projectTest
    name: projectTest
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: mockTest
        run: go test bookReadingNote/project/mock/myMock
#        go test bookReadingNote/project/mock/mockSample
