name: project
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
#    tags:
#      - v1
#  paths:
##    - 'test/*'
#    - 'bookReadingNote/project/mock/mockSample'

jobs:
  build:
    # Job name is projectTest
    name: projectTest
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: use bookReadingNote
        uses: shanwenhao1/bookReadingNote
      - name: mockTest
        run: go test -v -coverprofile cover.out .\project\mock\myMock\
#        go test bookReadingNote/project/mock/mockSample
#  go test -v -coverprofile cover.out .\project\mock\myMock\
