name: microservice
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is microserviceTest
    name: microserviceTest
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'




##example: https://github.com/golangci/golangci-lint/blob/master/.github/workflows/pr.yml
#name: project
## This workflow is triggered on pushes to the repository.
#on:
#  push:
#    branches:
#      - master
#    tags:
#      - v*
#    pull_request:
##  paths:
###    - 'test/*'
##    - 'bookReadingNote/project/mock/mockSample'
#jobs:
#  build:
#    # Job name is microserviceTest
#    name: project Test
#    # This job runs on Linux
#    runs-on: ubuntu-latest
#    steps:
#      # The checkout action is a standard action that you must include in your workflow before other actions when
#      # This step checks out a copy of your repository.
#      - uses: actions/checkout@v2
#      - name: project
#        uses: shanwenhao1/bookReadingNote@v1
#        with:
#          version: latest
#      # This step prints an output (time) from the previous step's action.
#      - name: mock Test
#        run: go test -v -coverprofile cover.out bookReadingNote\project\mock\myMock








#jobs:
#  # We already run the current project in tests, but here we test
#  # our GitHub action with the latest stable project.
#  bookReadingNote:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: note
#        uses: shanwenhao1/bookReadingNote@v1
#        with:
#          version: latest
#  Test:
#    needs: bookReadingNote # run after bookReadingNote action to not produce duplicated errors
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        golang:
#          - 1.15
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.golang }} # test only the latest go version to speed up CI
#      - uses: actions/cache@v2
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-${{ matrix.golang }}-
#      - name: mock Test
#        run: go test -v -coverprofile cover.out bookReadingNote\project\mock\myMock
